# Generated by Django 5.2.6 on 2025-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('TDL', 'TDL'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
