# Generated by Django 5.2.6 on 2025-09-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0003_contactquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
